images = {'Новиград': 'https://disk.yandex.ru/i/h5X7bFL5Yq3S6w',
          'Скелиге': 'https://disk.yandex.ru/i/nIwj3SKexCUKEQ',
          'Ундвик1': 'https://disk.yandex.ru/i/7bvx_JC1OpplFQ',
          'Ундвик2': 'https://disk.yandex.ru/i/TdPfID2_EY4Sjg',
          'меч': 'https://disk.yandex.ru/i/lsjZ7XKgkVShqw',
          'тронный зал': 'https://disk.yandex.ru/i/viYnTBKeX59pCQ',
          'место нападения': 'https://disk.yandex.ru/i/A4TDItczLeXGqA',
          'убежище Таулера': 'https://disk.yandex.ru/i/wk7eW2WIoo12jw',
          'логово вампира': 'https://disk.yandex.ru/i/Fvzgg4WcRs20kA',
          'корчма': 'https://disk.yandex.ru/i/xO_-8yep2UpFww',
          'Каер Морхен': 'https://disk.yandex.ru/i/YiqQF4klZ2bjjw',
          'таверна': 'https://disk.yandex.ru/i/WvheRvPegCRpEw'}
